name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Set up .env file
      run: |
          echo "DB_HOST=127.0.0.1" > .env
          echo "DB_USER=admin" >> .env
          echo "DB_PASSWORD=secret" >> .env
          echo "Created .env file with contents:"
          cat .env
    - name: Move .env to build/tests directory
      run: |
        # mkdir -p build/tests
        mv .env build/tests/.env
        echo "Moved .env file to build/tests directory:"
        ls build/tests
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

